import DragProvider from '@contexts/DragProvider';
import StyleProvider from '@contexts/StyleProvider';
import { EditorProvider } from '@hooks/useEditor';
import { Editor } from '@organisms/Editor';
import GlobalStyles from '@styles/globalStyles';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <StyleProvider>
          <GlobalStyles />
          <DragProvider>
            <EditorProvider>
              <Editor />
            </EditorProvider>
          </DragProvider>
        </StyleProvider>
      </main>
    </>
  );
}
